PHOTO_FOLDER = 'static/photos'
WORD_CSV_FOLDER_IN = 'static/words_csv_in'
SOCIAL_CSV_FOLDER_IN = 'static/social_csv_in'
WORD_CSV_FOLDER_OUT = 'static/words_csv_out'
SOCIAL_CSV_FOLDER_OUT= 'static/social_csv_out'
